language: c

services:
  - docker

env:
  matrix:
    - PUSH_IMAGE=1 MAKE_PKG=1 OS=ubuntu OS_VER=16.04
    - PUSH_IMAGE=1 MAKE_PKG=1 OS=fedora OS_VER=25
    - MAKE_PKG=0 OS=ubuntu OS_VER=16.04 C_COMPILER=clang CPP_COMPILER=clang++
    - MAKE_PKG=0 OS=fedora OS_VER=25    C_COMPILER=clang CPP_COMPILER=clang++
    - MAKE_PKG=0 OS=ubuntu OS_VER=16.04
    - MAKE_PKG=0 OS=fedora OS_VER=25
    - MAKE_PKG=0 CAPSTONE_EXPERIMENTAL=1 OS=ubuntu OS_VER=16.04
    - COVERITY=1 OS=ubuntu OS_VER=16.04
    - COVERAGE=1 OS=ubuntu OS_VER=16.04

before_install:
  - export HOST_WORKDIR=`pwd`
  - export GITHUB_REPO=${GITHUB_REPO:-pmem/syscall_intercept}
  - export DOCKERHUB_REPO=${DOCKERHUB_REPO:-pmem/syscall_intercept}
  - export PROJECT=syscall_intercept
  - export EXTRA_DOCKER_ARGS=-t
  - cd utils/docker
  - ./pull-or-rebuild-image.sh
  - if [[ -f push_image_to_repo_flag ]]; then PUSH_THE_IMAGE=1; fi
  - rm -f push_image_to_repo_flag

script:
  - ./build.sh

after_success:
  - if [[ $PUSH_THE_IMAGE -eq 1 ]]; then images/push-image.sh $OS-$OS_VER; fi
